import { VITRIN_WEBAPP_CONSTANT, DARAMAD_WEBAPP_CONSTANT, DOBARE_WEBAPP_CONSTANT } from "@saas/utils/constants";

export const DOBARE_SUPPORT_TEAM_PHONE_NUMBER = "+982191070754";
export const DARAMAD_SUPPORT_TEAM_PHONE_NUMBER = "+989912982731";
export const VITRIN_SUPPORT_TEAM_PHONE_NUMBER = "+982191070751";

export const supportTeamPhone = {
  [DOBARE_WEBAPP_CONSTANT]: DOBARE_SUPPORT_TEAM_PHONE_NUMBER,
  [VITRIN_WEBAPP_CONSTANT]: VITRIN_SUPPORT_TEAM_PHONE_NUMBER,
  [DARAMAD_WEBAPP_CONSTANT]: DARAMAD_SUPPORT_TEAM_PHONE_NUMBER,
};
