import uniqueId from "lodash/uniqueId";

export const categories = [
  { label: "رستوران و کافه", id: 1 },
  { label: "لوازم دیجیتال", id: 2 },
  { label: "ابزار آلات", id: 3 },
  { label: "پوشاک", id: 4 },
  { label: "سوپر پروتئین", id: 5 },
  { label: "شیرینی فروشی", id: 6 },
  { label: "شرکتی", id: 7 },
  { label: "پزشکی", id: 8 },
  { label: "سالن زیبایی", id: 9 },
  { label: "تجهیزات صنعتی", id: 10 },
];

export const example_businesses = [
  {
    title: "فروشگاهی",
    label: "shopping",
    id: uniqueId(),
    logo: "/images/shopping.png",
    items: [
      {
        id: uniqueId(),
        image: "/images/1-1-cakekhoone.jpg",
        name: "کیک خونه",
        alt: "سایت کیک خونه - طراحی شده با ویترین",
        link: "https://cakeekhooneh.com/",
      },
      {
        id: uniqueId(),
        image: "/images/1-3-asuabzar.jpg",
        name: "آسو ابزار",
        alt: "سایت آسو ابزار - طراحی شده با ویترین",
        link: "https://asuabzar.com/",
      },
      {
        id: uniqueId(),
        image: "/images/1-4-proland.jpg",
        name: "سوپر پروتئین پرولند",
        alt: "سایت سوپر پروتئین پرولند - طراحی شده با ویترین",
        link: "https://prolandprotein.ir/",
      },
      {
        id: uniqueId(),
        image: "/images/1-5-abzaroxin.jpg",
        name: "ابزار اکسین",
        alt: "سایت ابزار اکسین - طراحی شده با ویترین",
        link: "https://abzaroxin.com/",
      },
      {
        id: uniqueId(),
        image: "/images/1-8-payedigesadat.jpg",
        name: "پای دیگ سادات",
        alt: "سایت پای دیگ سادات - طراحی شده با ویترین",
        link: "https://payedigesadat.com/",
      },
      {
        id: uniqueId(),
        image: "/images/1-11-soofche.jpg",
        name: "ادویه سوفچه",
        alt: "سایت ادویه سوفچه - طراحی شده با ویترین",
        link: "https://sofcheh.ir/",
      },
    ],
    catgory: [
      { label: "رستوران" },
      { label: "فست فود" },
      { label: "کافی شاپ" },
      { label: "ابزار آلات" },
      { label: "لوازم دیجیتال" },
      { label: "مواد غذایی" },
      { label: "پوشاک" },
      { label: "کیک و شیرینی" },
      { label: "کودک" },
      { label: "گل و گیاه" },
      { label: "صنعتی" },
    ],
  },
  {
    id: uniqueId(),
    label: "restaurant",
    title: "رستوران و کافه",
    logo: "/images/Restaurant.png",
    items: [
      {
        id: uniqueId(),
        image: "/images/2-1-cleanfood.jpg",
        name: "کلین فود",
        alt: "سایت کلین فود - طراحی شده با ویترین",
        link: "https://cleanfoods.ir/",
      },
      {
        id: uniqueId(),
        image: "/images/2-2-ashdarchin.jpg",
        name: "آشکده دارچین",
        alt: "سایت آشکده دارچین - طراحی شده با ویترین",
        link: "https://ashdarchin.com/",
      },
      {
        id: uniqueId(),
        image: "/images/2-3-sarzaminsookhari.jpg",
        name: "سرزمین سوخاری",
        alt: "سایت سرزمین سوخاری - طراحی شده با ویترین",
        link: "https://sarzaminesookhari.com/",
      },
      {
        id: uniqueId(),
        image: "/images/2-4-gilane.jpg",
        name: "رستوران گیلانه",
        alt: "سایت گیلانه - طراحی شده با ویترین",
        link: "https://gilaneh-restaurant.ir/",
      },
      {
        id: uniqueId(),
        image: "/images/2-5-tarighatshariati.jpg",
        name: "رستوران طریقت (شریعتی)",
        alt: "سایت رستوران طریقت (شریعتی) - طراحی شده با ویترین",
        link: "https://tarighatshariati.com/",
      },
      {
        id: uniqueId(),
        image: "/images/2-6-river.jpg",
        name: "رستوران ایتالیایی ریور",
        alt: "سایت رستوران ایتالیایی ریور - طراحی شده با ویترین",
        link: "https://river-restaurant.com/",
      },
      {
        id: uniqueId(),
        image: "/images/2-7-chopchop.jpg",
        name: "رستوران چاپ چاپ",
        alt: "سایت رستوران چاپ چاپ - طراحی شده با ویترین",
        link: "https://chopchopasia.com/",
      },
      {
        id: uniqueId(),
        image: "/images/2-8-bambooexpress.jpg",
        name: " بامبو اکسپرس",
        alt: "سایت بامبو اکسپرس - طراحی شده با ویترین",
        link: "https://bambooexp.com/",
      },
    ],
  },
  {
    id: uniqueId(),
    label: "digital",
    title: "لوازم دیجیتال",
    logo: "/images/DigitalGoods.png",
    items: [
      {
        id: uniqueId(),
        image: "/images/3-1-imc.jpg",
        name: " فروشگاه آنلاین IMC",
        alt: "سایت فروشگاه آنلاین IMC - طراحی شده با ویترین",
        link: "https://imc.ir/",
      },
      {
        id: uniqueId(),
        image: "/images/3-3-onlineroshan.jpg",
        name: "فروشگاه آنلاین روشن",
        alt: "سایت فروشگاه آنلاین روشن - طراحی شده با ویترین",
        link: "https://r-market.ir/",
      },
      {
        id: uniqueId(),
        image: "/images/3-4-fadak.jpg",
        name: "فروشگاه فدک",
        alt: "سایت فروشگاه فدک - طراحی شده با ویترین",
        link: "https://fadakst.ir/",
      },
    ],
  },
  {
    id: uniqueId(),
    label: "clothing",
    title: "پوشاک",
    logo: "/images/Clothing.png",
    items: [
      {
        id: uniqueId(),
        image: "/images/4-2-poone.jpg",
        name: "Poone Clothing",
        alt: "سایت Poone Clothing - طراحی شده با ویترین",
        link: "https://pooneclothing.ir/",
      },
      {
        id: uniqueId(),
        image: "/images/4-3-jutehomeland.jpg",
        name: "جوت هوملند",
        alt: "سایت جوت هوملند - طراحی شده با ویترین",
        link: "https://jutehomeland.ir/",
      },
      {
        id: uniqueId(),
        image: "/images/4-4-boojanshop.jpg",
        name: "بوژان شاپ",
        alt: "سایت بوژان شاپ - طراحی شده با ویترین",
        link: "https://boojanshop.com/",
      },
      {
        id: uniqueId(),
        image: "/images/4-5-jeandarc.jpg",
        name: "شال و روسری ژاندارک",
        link: "https://jeannedarc-scarf.com/",
        alt: "سایت شال و روسری ژاندارک - طراحی شده با ویترین",
      },
    ],
  },
  {
    id: uniqueId(),
    label: "corporate",
    title: "شرکتی و معرفی",
    logo: "/images/intro.png",
    items: [
      {
        id: uniqueId(),
        image: "/images/5-1-drmojdeyusefi.jpg",
        name: "دکتر مژده یوسفی",
        alt: "سایت دکتر مژده یوسفی - طراحی شده با ویترین",
        link: "https://drmojdehyousefi.com/",
      },
      {
        id: uniqueId(),
        image: "/images/5-2-irankgf.jpg",
        name: "شرکت کاوش گستر فانیذ",
        alt: "سایت شرکت کاوش گستر فانیذ - طراحی شده با ویترین",
        link: "https://irankgf.com/",
      },
      {
        id: uniqueId(),
        image: "/images/5-3-viptaxi.jpg",
        name: " تاکسی VIP همسفران",
        alt: "سایت تاکسی VIP همسفران - طراحی شده با ویترین",
        link: "https://hamsafarantaxi.com/",
      },
      {
        id: uniqueId(),
        image: "/images/5-4-sanataria.jpg",
        name: "صنعت آریا",
        alt: "سایت صنعت آریا - طراحی شده با ویترین",
        link: "https://sanatariya.ir/",
      },
      {
        id: uniqueId(),
        image: "/images/5-5-bimekosar.jpg",
        name: " نمایندگی بیمه کوثر احمدزاده",
        alt: "سایت نمایندگی بیمه کوثر احمدزاده - طراحی شده با ویترین",
        link: "https://kosarinsurance.com/",
      },
    ],
  },
];
