import { CDN_BASE_URL } from "@saas/utils/api";

const image_url = `${CDN_BASE_URL}mock-bag.svg`;
const image = `${CDN_BASE_URL}mock-bag.svg`;
const thumbnail_url = `${CDN_BASE_URL}mock-bag.svg`;
const main_image_url = `${CDN_BASE_URL}mock-bag.svg`;
const main_image_thumbnail_url = `${CDN_BASE_URL}mock-bag.svg`;

export const mockMenu = {
  currentId: 31,
  id: 0,
  categories: [],
  children: [
    {
      id: 1,
      name: "موبایل",
      parent: 0,
      children: [
        {
          id: 5,
          name: "سامسونگ",
          parent: 1,
          children: [],
          categories: [161802],
          conjoined: false,
          image: "https://hs3-cdn-saas.behtarino.com/media/business_images/sam.jpg",
        },
        {
          id: 6,
          name: "آیفون",
          parent: 1,
          children: [],
          categories: [161809],
          conjoined: false,
          image:
            "https://hs3-cdn-saas.behtarino.com/media/business_images/c81a8a37df5f464270e483847e86b7f6.jpg",
        },
        {
          id: 9,
          name: "شیائومی",
          parent: 1,
          children: [],
          categories: [162422],
          conjoined: false,
          image: "https://hs3-cdn-saas.behtarino.com/media/business_images/mi.jpg",
        },
        {
          id: 10,
          name: "نوکیا",
          parent: 1,
          children: [],
          categories: [162431],
          conjoined: false,
          image:
            "https://hs3-cdn-saas.behtarino.com/media/business_images/nokia228.jpg",
        },
        {
          id: 11,
          name: "هوآوی",
          parent: 1,
          children: [],
          categories: [162423],
          conjoined: false,
          image:
            "https://hs3-cdn-saas.behtarino.com/media/business_images/huawei.jpg",
        },
        {
          id: 12,
          name: "موتورولا",
          parent: 1,
          children: [],
          categories: [166099],
          conjoined: false,
          image:
            "https://hs3-cdn-saas.behtarino.com/media/business_images/motorola.jpg",
        },
        {
          id: 13,
          name: "وان پلاس",
          parent: 1,
          children: [],
          categories: [166100],
          conjoined: false,
          image:
            "https://hs3-cdn-saas.behtarino.com/media/business_images/4dea3e05c6b9598c9e47da872efa5585.jpg",
        },
        {
          id: 14,
          name: "آنر",
          parent: 1,
          children: [],
          categories: [166101],
          conjoined: false,
          image: "https://hs3-cdn-saas.behtarino.com/media/business_images/crop.jpg",
        },
        {
          id: 15,
          name: "بلک بری",
          parent: 1,
          children: [],
          categories: [166102],
          conjoined: false,
          image: "https://hs3-cdn-saas.behtarino.com/media/business_images/bb.jpg",
        },
        {
          id: 29,
          name: "ال جی",
          parent: 1,
          children: [],
          categories: [168655],
          conjoined: false,
          seo: {},
        },
      ],
      categories: [161797],
      conjoined: true,
      image:
        "https://hs3-cdn-saas.behtarino.com/media/business_images/apple-iphone-12-pro-max-dual-sim-256gb-ram-6gb-mobile-phone620.jpg",
    },
    {
      id: 2,
      name: "لپ تاپ",
      parent: 0,
      children: [],
      categories: [161798],
      conjoined: true,
      image:
        "https://hs3-cdn-saas.behtarino.com/media/business_images/download697.jpg",
    },
    {
      id: 3,
      name: "اسپیکر",
      parent: 0,
      children: [],
      categories: [161799],
      conjoined: true,
      image:
        "https://hs3-cdn-saas.behtarino.com/media/business_images/tsco-ts-2187-desktop-wired-speaker774.jpg",
    },
    {
      id: 4,
      name: "انواع قاب",
      parent: 0,
      children: [],
      categories: [161800],
      conjoined: true,
      image:
        "https://hs3-cdn-saas.behtarino.com/media/business_images/phone-case386.jpg",
    },
    {
      id: 7,
      name: "هدفون و هندزفری",
      parent: 0,
      children: [],
      categories: [161801],
      conjoined: true,
      image:
        "https://hs3-cdn-saas.behtarino.com/media/business_images/wp3011943-1024x619769.jpg",
    },
    {
      id: 16,
      name: "ساعت هوشمند",
      parent: 0,
      children: [
        {
          id: 17,
          name: "ساعت هوشمند شیائومی",
          parent: 16,
          children: [],
          categories: [166106],
          conjoined: false,
          image:
            "https://hs3-cdn-saas.behtarino.com/media/business_images/mi-wth.jpg",
        },
        {
          id: 18,
          name: "ساعت هوشمند سامسونگ",
          parent: 16,
          children: [],
          categories: [166107],
          conjoined: false,
          image:
            "https://hs3-cdn-saas.behtarino.com/media/business_images/06c8c139dd97fffae88ab7a3c717694a.jpg",
        },
        {
          id: 19,
          name: "ساعت هوشمند اپل",
          parent: 16,
          children: [],
          categories: [166103],
          conjoined: false,
          image:
            "https://hs3-cdn-saas.behtarino.com/media/business_images/222477.jpg",
        },
      ],
      categories: [166110],
      conjoined: true,
      image: "",
    },
    {
      id: 20,
      name: "تبلت",
      parent: 0,
      children: [
        {
          id: 23,
          name: "تبلت سامسونگ",
          parent: 20,
          children: [],
          categories: [167119],
          conjoined: true,
          image:
            "https://hs3-cdn-saas.behtarino.com/media/business_images/sam-gal.jpg",
        },
        {
          id: 24,
          name: "ای پد",
          parent: 20,
          children: [],
          categories: [167120],
          conjoined: true,
          image:
            "https://hs3-cdn-saas.behtarino.com/media/business_images/22222222.jpg",
        },
      ],
      categories: [166111],
      conjoined: true,
    },
    {
      id: 22,
      name: "کنسول بازی",
      parent: 0,
      children: [
        {
          id: 25,
          name: "Microsoft Xbox",
          parent: 22,
          children: [],
          categories: [167101],
          conjoined: true,
          image:
            "https://hs3-cdn-saas.behtarino.com/media/business_images/xbox-logo.jpg",
        },
        {
          id: 26,
          name: "Playstation",
          parent: 22,
          children: [],
          categories: [166108],
          conjoined: true,
          image: "https://hs3-cdn-saas.behtarino.com/media/business_images/ps.jpg",
        },
        {
          id: 28,
          name: "dual sense PS5",
          parent: 22,
          children: [],
          categories: [167728],
          conjoined: true,
          seo: {},
        },
      ],
      categories: [166108, 167101],
      conjoined: true,
      image: "",
    },
    {
      id: 27,
      name: "ایر پاد",
      parent: 0,
      children: [],
      categories: [166105],
      conjoined: true,
    },
    {
      id: 30,
      name: "abc",
      parent: 0,
      children: [],
      categories: [171234],
      conjoined: false,
      seo: {},
    },
  ],
};
export const mockCategories = [
  {
    id: 1,
    super_label_id: null,
    title: "موبایل",
    order: 0,
    extra_data: {},
    seo: {
      index: true,
    },
  },
  {
    id: 2,
    super_label_id: null,
    title: "لوازم جانبی",
    order: 1,
    extra_data: {},
    seo: {
      index: true,
    },
  },
  {
    id: 3,
    super_label_id: null,
    title: "کامپیوتر",
    order: 2,
    extra_data: {},
    seo: {
      index: true,
    },
  },
  {
    id: 4,
    super_label_id: null,
    title: "هدفون",
    order: 3,
    extra_data: {},
    seo: {
      index: true,
    },
  },
  {
    id: 5,
    super_label_id: null,
    title: "کنسول بازی",
    order: 4,
    extra_data: {},
    seo: {
      index: true,
    },
  },
  {
    id: 6,
    super_label_id: null,
    title: "دوربین",
    order: 5,
    extra_data: {},
    seo: {
      index: true,
    },
  },
];

export const mockProducts = [
  {
    id: 6216884,
    sku: null,
    unit: "number",
    priority: 100,
    super_resource: null,
    title: "کانسیلر میبلین فیت می",
    business: 1969986,
    description:
      "<p>کانسیلر فیت می&nbsp;میبلین بافت نرم و سبک این کانسیلر به راحتی روی پوست می نشیند و ظاهری طبیعی به آن می دهد</p><p><br></p><p>☆پوشش دهی مناسب</p><p>☆بدون ماسیده شدن روی پوست</p><p>☆مناسب برای پوشش لک و پف زیر چشم</p><p>☆پوشاننده ی حلقه های تیره و قرمزی های پوست</p><p>☆ضد حساسیت</p><p>☆فاقد چربی</p><p>☆بدون بو</p><p>☆حجم : 6.8 میل</p><p>☆ساخت کشور فرانسه</p>",
    labels: [568562, 568575, 574997],
    extra_data: {
      config: {
        is_saleable: true,
      },
      info_table: [],
      similar_products: {
        conjoined: false,
        categories: [568562],
      },
    },
    seo: {},
    multi_lang_data: {},
    is_active: true,
    variants_data: [],
    available: true,
    images: [
      {
        id: 4069,
        variation: 17241,
        image,
        thumbnail_url,
        image_url,
        order: 0,
      },
    ],
    default_variation: {
      id: 17241,
      resource: 6216884,
      resource_type: "product",
      sku: null,
      title: "کانسیلر میبلین فیت می",
      images: [],
      main_image_url,
      main_image_thumbnail_url,
      minimum_choice: null,
      maximum_choice: null,
      final_unit_cost: null,
      extra_data: {
        isSuper: false,
      },
      initial_price: 295000,
      discounted_price: 295000,
      packaging_price: 0,
      inventory_count: 0,
      keep_selling: true,
      threshold: 0,
      alerting: false,
      created_at: "2022-06-26T12:48:33.440876Z",
      updated_at: "2022-06-26T12:54:32.177186Z",
      is_active: true,
      available: true,
    },
    minimum_choice: null,
    maximum_choice: null,
    variations: [
      {
        id: 17241,
        resource: 6216884,
        resource_type: "product",
        sku: null,
        title: "کانسیلر میبلین فیت می",
        minimum_choice: null,
        maximum_choice: null,
        final_unit_cost: null,
        extra_data: {
          isSuper: false,
        },
        initial_price: 295000,
        discounted_price: 295000,
        packaging_price: 0,
        inventory_count: 0,
        keep_selling: true,
        threshold: 0,
        alerting: false,
        created_at: "2022-06-26T12:48:33.440876Z",
        updated_at: "2022-06-26T12:54:32.177186Z",
        is_active: true,
        available: true,
        modifier_sets: [],
        images: [
          {
            id: 4069,
            variation: 17241,
            image,
            thumbnail_url,
            image_url,
            order: 0,
          },
        ],
        main_image_url,
        main_image_thumbnail_url,
      },
    ],
    main_image_thumbnail_url,
  },
  {
    id: 6216884,
    sku: null,
    unit: "number",
    priority: 100,
    super_resource: null,
    title: "کانسیلر میبلین فیت می",
    business: 1969986,
    description:
      "<p>کانسیلر فیت می&nbsp;میبلین بافت نرم و سبک این کانسیلر به راحتی روی پوست می نشیند و ظاهری طبیعی به آن می دهد</p><p><br></p><p>☆پوشش دهی مناسب</p><p>☆بدون ماسیده شدن روی پوست</p><p>☆مناسب برای پوشش لک و پف زیر چشم</p><p>☆پوشاننده ی حلقه های تیره و قرمزی های پوست</p><p>☆ضد حساسیت</p><p>☆فاقد چربی</p><p>☆بدون بو</p><p>☆حجم : 6.8 میل</p><p>☆ساخت کشور فرانسه</p>",
    labels: [568562, 568575, 574997],
    extra_data: {
      config: {
        is_saleable: true,
      },
      info_table: [],
      similar_products: {
        conjoined: false,
        categories: [568562],
      },
    },
    seo: {},
    multi_lang_data: {},
    is_active: true,
    variants_data: [],
    available: true,
    default_variation: {
      id: 17241,
      resource: 6216884,
      resource_type: "product",
      sku: null,
      title: "کانسیلر میبلین فیت می",
      images: [
        {
          id: 4069,
          variation: 17241,
          image,
          thumbnail_url,
          image_url,
          order: 0,
        },
      ],
      main_image_url,
      main_image_thumbnail_url,
      minimum_choice: null,
      maximum_choice: null,
      final_unit_cost: null,
      extra_data: {
        isSuper: false,
      },
      initial_price: 295000,
      discounted_price: 295000,
      packaging_price: 0,
      inventory_count: 0,
      keep_selling: true,
      threshold: 0,
      alerting: false,
      created_at: "2022-06-26T12:48:33.440876Z",
      updated_at: "2022-06-26T12:54:32.177186Z",
      is_active: true,
      available: true,
    },
    minimum_choice: null,
    maximum_choice: null,
    variations: [
      {
        id: 17241,
        resource: 6216884,
        resource_type: "product",
        sku: null,
        title: "کانسیلر میبلین فیت می",
        minimum_choice: null,
        maximum_choice: null,
        final_unit_cost: null,
        extra_data: {
          isSuper: false,
        },
        initial_price: 295000,
        discounted_price: 295000,
        packaging_price: 0,
        inventory_count: 0,
        keep_selling: true,
        threshold: 0,
        alerting: false,
        created_at: "2022-06-26T12:48:33.440876Z",
        updated_at: "2022-06-26T12:54:32.177186Z",
        is_active: true,
        available: true,
        modifier_sets: [],
        images: [
          {
            id: 4069,
            variation: 17241,
            image,
            thumbnail_url,
            image_url,
            order: 0,
          },
        ],
        main_image_url,
        main_image_thumbnail_url,
      },
    ],
    main_image_thumbnail_url,
  },
  {
    id: 6216884,
    sku: null,
    unit: "number",
    priority: 100,
    super_resource: null,
    title: "کانسیلر میبلین فیت می",
    business: 1969986,
    description:
      "<p>کانسیلر فیت می&nbsp;میبلین بافت نرم و سبک این کانسیلر به راحتی روی پوست می نشیند و ظاهری طبیعی به آن می دهد</p><p><br></p><p>☆پوشش دهی مناسب</p><p>☆بدون ماسیده شدن روی پوست</p><p>☆مناسب برای پوشش لک و پف زیر چشم</p><p>☆پوشاننده ی حلقه های تیره و قرمزی های پوست</p><p>☆ضد حساسیت</p><p>☆فاقد چربی</p><p>☆بدون بو</p><p>☆حجم : 6.8 میل</p><p>☆ساخت کشور فرانسه</p>",
    labels: [568562, 568575, 574997],
    extra_data: {
      config: {
        is_saleable: true,
      },
      info_table: [],
      similar_products: {
        conjoined: false,
        categories: [568562],
      },
    },
    seo: {},
    multi_lang_data: {},
    is_active: true,
    variants_data: [],
    available: true,
    default_variation: {
      id: 17241,
      resource: 6216884,
      resource_type: "product",
      sku: null,
      title: "کانسیلر میبلین فیت می",
      images: [
        {
          id: 4069,
          variation: 17241,
          image,
          thumbnail_url,
          image_url,
          order: 0,
        },
      ],
      main_image_url,
      main_image_thumbnail_url,
      minimum_choice: null,
      maximum_choice: null,
      final_unit_cost: null,
      extra_data: {
        isSuper: false,
      },
      initial_price: 295000,
      discounted_price: 295000,
      packaging_price: 0,
      inventory_count: 0,
      keep_selling: true,
      threshold: 0,
      alerting: false,
      created_at: "2022-06-26T12:48:33.440876Z",
      updated_at: "2022-06-26T12:54:32.177186Z",
      is_active: true,
      available: true,
    },
    minimum_choice: null,
    maximum_choice: null,
    variations: [
      {
        id: 17241,
        resource: 6216884,
        resource_type: "product",
        sku: null,
        title: "کانسیلر میبلین فیت می",
        minimum_choice: null,
        maximum_choice: null,
        final_unit_cost: null,
        extra_data: {
          isSuper: false,
        },
        initial_price: 295000,
        discounted_price: 295000,
        packaging_price: 0,
        inventory_count: 0,
        keep_selling: true,
        threshold: 0,
        alerting: false,
        created_at: "2022-06-26T12:48:33.440876Z",
        updated_at: "2022-06-26T12:54:32.177186Z",
        is_active: true,
        available: true,
        modifier_sets: [],
        images: [
          {
            id: 4069,
            variation: 17241,
            image,
            thumbnail_url,
            image_url,
            order: 0,
          },
        ],
        main_image_url,
        main_image_thumbnail_url,
      },
    ],
    main_image_thumbnail_url,
  },
  {
    id: 6216884,
    sku: null,
    unit: "number",
    priority: 100,
    super_resource: null,
    title: "کانسیلر میبلین فیت می",
    business: 1969986,
    description:
      "<p>کانسیلر فیت می&nbsp;میبلین بافت نرم و سبک این کانسیلر به راحتی روی پوست می نشیند و ظاهری طبیعی به آن می دهد</p><p><br></p><p>☆پوشش دهی مناسب</p><p>☆بدون ماسیده شدن روی پوست</p><p>☆مناسب برای پوشش لک و پف زیر چشم</p><p>☆پوشاننده ی حلقه های تیره و قرمزی های پوست</p><p>☆ضد حساسیت</p><p>☆فاقد چربی</p><p>☆بدون بو</p><p>☆حجم : 6.8 میل</p><p>☆ساخت کشور فرانسه</p>",
    labels: [568562, 568575, 574997],
    extra_data: {
      config: {
        is_saleable: true,
      },
      info_table: [],
      similar_products: {
        conjoined: false,
        categories: [568562],
      },
    },
    seo: {},
    multi_lang_data: {},
    is_active: true,
    variants_data: [],
    available: true,
    default_variation: {
      id: 17241,
      resource: 6216884,
      resource_type: "product",
      sku: null,
      title: "کانسیلر میبلین فیت می",
      images: [
        {
          id: 4069,
          variation: 17241,
          image,
          thumbnail_url,
          image_url,
          order: 0,
        },
      ],
      main_image_url,
      main_image_thumbnail_url,
      minimum_choice: null,
      maximum_choice: null,
      final_unit_cost: null,
      extra_data: {
        isSuper: false,
      },
      initial_price: 295000,
      discounted_price: 295000,
      packaging_price: 0,
      inventory_count: 0,
      keep_selling: true,
      threshold: 0,
      alerting: false,
      created_at: "2022-06-26T12:48:33.440876Z",
      updated_at: "2022-06-26T12:54:32.177186Z",
      is_active: true,
      available: true,
    },
    minimum_choice: null,
    maximum_choice: null,
    variations: [
      {
        id: 17241,
        resource: 6216884,
        resource_type: "product",
        sku: null,
        title: "کانسیلر میبلین فیت می",
        minimum_choice: null,
        maximum_choice: null,
        final_unit_cost: null,
        extra_data: {
          isSuper: false,
        },
        initial_price: 295000,
        discounted_price: 295000,
        packaging_price: 0,
        inventory_count: 0,
        keep_selling: true,
        threshold: 0,
        alerting: false,
        created_at: "2022-06-26T12:48:33.440876Z",
        updated_at: "2022-06-26T12:54:32.177186Z",
        is_active: true,
        available: true,
        modifier_sets: [],
        images: [
          {
            id: 4069,
            variation: 17241,
            image,
            thumbnail_url,
            image_url,
            order: 0,
          },
        ],
        main_image_url,
        main_image_thumbnail_url,
      },
    ],
    main_image_thumbnail_url,
  },
  {
    id: 6216884,
    sku: null,
    unit: "number",
    priority: 100,
    super_resource: null,
    title: "کانسیلر میبلین فیت می",
    business: 1969986,
    description:
      "<p>کانسیلر فیت می&nbsp;میبلین بافت نرم و سبک این کانسیلر به راحتی روی پوست می نشیند و ظاهری طبیعی به آن می دهد</p><p><br></p><p>☆پوشش دهی مناسب</p><p>☆بدون ماسیده شدن روی پوست</p><p>☆مناسب برای پوشش لک و پف زیر چشم</p><p>☆پوشاننده ی حلقه های تیره و قرمزی های پوست</p><p>☆ضد حساسیت</p><p>☆فاقد چربی</p><p>☆بدون بو</p><p>☆حجم : 6.8 میل</p><p>☆ساخت کشور فرانسه</p>",
    labels: [568562, 568575, 574997],
    extra_data: {
      config: {
        is_saleable: true,
      },
      info_table: [],
      similar_products: {
        conjoined: false,
        categories: [568562],
      },
    },
    seo: {},
    multi_lang_data: {},
    is_active: true,
    variants_data: [],
    available: true,
    default_variation: {
      id: 17241,
      resource: 6216884,
      resource_type: "product",
      sku: null,
      title: "کانسیلر میبلین فیت می",
      images: [
        {
          id: 4069,
          variation: 17241,
          image,
          thumbnail_url,
          image_url,
          order: 0,
        },
      ],
      main_image_url,
      main_image_thumbnail_url,
      minimum_choice: null,
      maximum_choice: null,
      final_unit_cost: null,
      extra_data: {
        isSuper: false,
      },
      initial_price: 295000,
      discounted_price: 295000,
      packaging_price: 0,
      inventory_count: 0,
      keep_selling: true,
      threshold: 0,
      alerting: false,
      created_at: "2022-06-26T12:48:33.440876Z",
      updated_at: "2022-06-26T12:54:32.177186Z",
      is_active: true,
      available: true,
    },
    minimum_choice: null,
    maximum_choice: null,
    variations: [
      {
        id: 17241,
        resource: 6216884,
        resource_type: "product",
        sku: null,
        title: "کانسیلر میبلین فیت می",
        minimum_choice: null,
        maximum_choice: null,
        final_unit_cost: null,
        extra_data: {
          isSuper: false,
        },
        initial_price: 295000,
        discounted_price: 295000,
        packaging_price: 0,
        inventory_count: 0,
        keep_selling: true,
        threshold: 0,
        alerting: false,
        created_at: "2022-06-26T12:48:33.440876Z",
        updated_at: "2022-06-26T12:54:32.177186Z",
        is_active: true,
        available: true,
        modifier_sets: [],
        images: [
          {
            id: 4069,
            variation: 17241,
            image,
            thumbnail_url,
            image_url,
            order: 0,
          },
        ],
        main_image_url,
        main_image_thumbnail_url,
      },
    ],
    main_image_thumbnail_url,
  },
  {
    id: 6216884,
    sku: null,
    unit: "number",
    priority: 100,
    super_resource: null,
    title: "کانسیلر میبلین فیت می",
    business: 1969986,
    description:
      "<p>کانسیلر فیت می&nbsp;میبلین بافت نرم و سبک این کانسیلر به راحتی روی پوست می نشیند و ظاهری طبیعی به آن می دهد</p><p><br></p><p>☆پوشش دهی مناسب</p><p>☆بدون ماسیده شدن روی پوست</p><p>☆مناسب برای پوشش لک و پف زیر چشم</p><p>☆پوشاننده ی حلقه های تیره و قرمزی های پوست</p><p>☆ضد حساسیت</p><p>☆فاقد چربی</p><p>☆بدون بو</p><p>☆حجم : 6.8 میل</p><p>☆ساخت کشور فرانسه</p>",
    labels: [568562, 568575, 574997],
    extra_data: {
      config: {
        is_saleable: true,
      },
      info_table: [],
      similar_products: {
        conjoined: false,
        categories: [568562],
      },
    },
    seo: {},
    multi_lang_data: {},
    is_active: true,
    variants_data: [],
    available: true,
    default_variation: {
      id: 17241,
      resource: 6216884,
      resource_type: "product",
      sku: null,
      title: "کانسیلر میبلین فیت می",
      images: [
        {
          id: 4069,
          variation: 17241,
          image,
          thumbnail_url,
          image_url,
          order: 0,
        },
      ],
      main_image_url,
      main_image_thumbnail_url,
      minimum_choice: null,
      maximum_choice: null,
      final_unit_cost: null,
      extra_data: {
        isSuper: false,
      },
      initial_price: 295000,
      discounted_price: 295000,
      packaging_price: 0,
      inventory_count: 0,
      keep_selling: true,
      threshold: 0,
      alerting: false,
      created_at: "2022-06-26T12:48:33.440876Z",
      updated_at: "2022-06-26T12:54:32.177186Z",
      is_active: true,
      available: true,
    },
    minimum_choice: null,
    maximum_choice: null,
    variations: [
      {
        id: 17241,
        resource: 6216884,
        resource_type: "product",
        sku: null,
        title: "کانسیلر میبلین فیت می",
        minimum_choice: null,
        maximum_choice: null,
        final_unit_cost: null,
        extra_data: {
          isSuper: false,
        },
        initial_price: 295000,
        discounted_price: 295000,
        packaging_price: 0,
        inventory_count: 0,
        keep_selling: true,
        threshold: 0,
        alerting: false,
        created_at: "2022-06-26T12:48:33.440876Z",
        updated_at: "2022-06-26T12:54:32.177186Z",
        is_active: true,
        available: true,
        modifier_sets: [],
        images: [
          {
            id: 4069,
            variation: 17241,
            image,
            thumbnail_url,
            image_url,
            order: 0,
          },
        ],
        main_image_url,
        main_image_thumbnail_url,
      },
    ],
    main_image_thumbnail_url,
  },
  {
    id: 6216884,
    sku: null,
    unit: "number",
    priority: 100,
    super_resource: null,
    title: "کانسیلر میبلین فیت می",
    business: 1969986,
    description:
      "<p>کانسیلر فیت می&nbsp;میبلین بافت نرم و سبک این کانسیلر به راحتی روی پوست می نشیند و ظاهری طبیعی به آن می دهد</p><p><br></p><p>☆پوشش دهی مناسب</p><p>☆بدون ماسیده شدن روی پوست</p><p>☆مناسب برای پوشش لک و پف زیر چشم</p><p>☆پوشاننده ی حلقه های تیره و قرمزی های پوست</p><p>☆ضد حساسیت</p><p>☆فاقد چربی</p><p>☆بدون بو</p><p>☆حجم : 6.8 میل</p><p>☆ساخت کشور فرانسه</p>",
    labels: [568562, 568575, 574997],
    extra_data: {
      config: {
        is_saleable: true,
      },
      info_table: [],
      similar_products: {
        conjoined: false,
        categories: [568562],
      },
    },
    seo: {},
    multi_lang_data: {},
    is_active: true,
    variants_data: [],
    available: true,
    default_variation: {
      id: 17241,
      resource: 6216884,
      resource_type: "product",
      sku: null,
      title: "کانسیلر میبلین فیت می",
      images: [
        {
          id: 4069,
          variation: 17241,
          image,
          thumbnail_url,
          image_url,
          order: 0,
        },
      ],
      main_image_url,
      main_image_thumbnail_url,
      minimum_choice: null,
      maximum_choice: null,
      final_unit_cost: null,
      extra_data: {
        isSuper: false,
      },
      initial_price: 295000,
      discounted_price: 295000,
      packaging_price: 0,
      inventory_count: 0,
      keep_selling: true,
      threshold: 0,
      alerting: false,
      created_at: "2022-06-26T12:48:33.440876Z",
      updated_at: "2022-06-26T12:54:32.177186Z",
      is_active: true,
      available: true,
    },
    minimum_choice: null,
    maximum_choice: null,
    variations: [
      {
        id: 17241,
        resource: 6216884,
        resource_type: "product",
        sku: null,
        title: "کانسیلر میبلین فیت می",
        minimum_choice: null,
        maximum_choice: null,
        final_unit_cost: null,
        extra_data: {
          isSuper: false,
        },
        initial_price: 295000,
        discounted_price: 295000,
        packaging_price: 0,
        inventory_count: 0,
        keep_selling: true,
        threshold: 0,
        alerting: false,
        created_at: "2022-06-26T12:48:33.440876Z",
        updated_at: "2022-06-26T12:54:32.177186Z",
        is_active: true,
        available: true,
        modifier_sets: [],
        images: [
          {
            id: 4069,
            variation: 17241,
            image,
            thumbnail_url,
            image_url,
            order: 0,
          },
        ],
        main_image_url,
        main_image_thumbnail_url,
      },
    ],
    main_image_thumbnail_url,
  },
  {
    id: 6216884,
    sku: null,
    unit: "number",
    priority: 100,
    super_resource: null,
    title: "کانسیلر میبلین فیت می",
    business: 1969986,
    description:
      "<p>کانسیلر فیت می&nbsp;میبلین بافت نرم و سبک این کانسیلر به راحتی روی پوست می نشیند و ظاهری طبیعی به آن می دهد</p><p><br></p><p>☆پوشش دهی مناسب</p><p>☆بدون ماسیده شدن روی پوست</p><p>☆مناسب برای پوشش لک و پف زیر چشم</p><p>☆پوشاننده ی حلقه های تیره و قرمزی های پوست</p><p>☆ضد حساسیت</p><p>☆فاقد چربی</p><p>☆بدون بو</p><p>☆حجم : 6.8 میل</p><p>☆ساخت کشور فرانسه</p>",
    labels: [568562, 568575, 574997],
    extra_data: {
      config: {
        is_saleable: true,
      },
      info_table: [],
      similar_products: {
        conjoined: false,
        categories: [568562],
      },
    },
    seo: {},
    multi_lang_data: {},
    is_active: true,
    variants_data: [],
    available: true,
    default_variation: {
      id: 17241,
      resource: 6216884,
      resource_type: "product",
      sku: null,
      title: "کانسیلر میبلین فیت می",
      images: [
        {
          id: 4069,
          variation: 17241,
          image,
          thumbnail_url,
          image_url,
          order: 0,
        },
      ],
      main_image_url,
      main_image_thumbnail_url,
      minimum_choice: null,
      maximum_choice: null,
      final_unit_cost: null,
      extra_data: {
        isSuper: false,
      },
      initial_price: 295000,
      discounted_price: 295000,
      packaging_price: 0,
      inventory_count: 0,
      keep_selling: true,
      threshold: 0,
      alerting: false,
      created_at: "2022-06-26T12:48:33.440876Z",
      updated_at: "2022-06-26T12:54:32.177186Z",
      is_active: true,
      available: true,
    },
    minimum_choice: null,
    maximum_choice: null,
    variations: [
      {
        id: 17241,
        resource: 6216884,
        resource_type: "product",
        sku: null,
        title: "کانسیلر میبلین فیت می",
        minimum_choice: null,
        maximum_choice: null,
        final_unit_cost: null,
        extra_data: {
          isSuper: false,
        },
        initial_price: 295000,
        discounted_price: 295000,
        packaging_price: 0,
        inventory_count: 0,
        keep_selling: true,
        threshold: 0,
        alerting: false,
        created_at: "2022-06-26T12:48:33.440876Z",
        updated_at: "2022-06-26T12:54:32.177186Z",
        is_active: true,
        available: true,
        modifier_sets: [],
        images: [
          {
            id: 4069,
            variation: 17241,
            image,
            thumbnail_url,
            image_url,
            order: 0,
          },
        ],
        main_image_url,
        main_image_thumbnail_url,
      },
    ],
    main_image_thumbnail_url,
  },
  {
    id: 6216884,
    sku: null,
    unit: "number",
    priority: 100,
    super_resource: null,
    title: "کانسیلر میبلین فیت می",
    business: 1969986,
    description:
      "<p>کانسیلر فیت می&nbsp;میبلین بافت نرم و سبک این کانسیلر به راحتی روی پوست می نشیند و ظاهری طبیعی به آن می دهد</p><p><br></p><p>☆پوشش دهی مناسب</p><p>☆بدون ماسیده شدن روی پوست</p><p>☆مناسب برای پوشش لک و پف زیر چشم</p><p>☆پوشاننده ی حلقه های تیره و قرمزی های پوست</p><p>☆ضد حساسیت</p><p>☆فاقد چربی</p><p>☆بدون بو</p><p>☆حجم : 6.8 میل</p><p>☆ساخت کشور فرانسه</p>",
    labels: [568562, 568575, 574997],
    extra_data: {
      config: {
        is_saleable: true,
      },
      info_table: [],
      similar_products: {
        conjoined: false,
        categories: [568562],
      },
    },
    seo: {},
    multi_lang_data: {},
    is_active: true,
    variants_data: [],
    available: true,
    default_variation: {
      id: 17241,
      resource: 6216884,
      resource_type: "product",
      sku: null,
      title: "کانسیلر میبلین فیت می",
      images: [
        {
          id: 4069,
          variation: 17241,
          image,
          thumbnail_url,
          image_url,
          order: 0,
        },
      ],
      main_image_url,
      main_image_thumbnail_url,
      minimum_choice: null,
      maximum_choice: null,
      final_unit_cost: null,
      extra_data: {
        isSuper: false,
      },
      initial_price: 295000,
      discounted_price: 295000,
      packaging_price: 0,
      inventory_count: 0,
      keep_selling: true,
      threshold: 0,
      alerting: false,
      created_at: "2022-06-26T12:48:33.440876Z",
      updated_at: "2022-06-26T12:54:32.177186Z",
      is_active: true,
      available: true,
    },
    minimum_choice: null,
    maximum_choice: null,
    variations: [
      {
        id: 17241,
        resource: 6216884,
        resource_type: "product",
        sku: null,
        title: "کانسیلر میبلین فیت می",
        minimum_choice: null,
        maximum_choice: null,
        final_unit_cost: null,
        extra_data: {
          isSuper: false,
        },
        initial_price: 295000,
        discounted_price: 295000,
        packaging_price: 0,
        inventory_count: 0,
        keep_selling: true,
        threshold: 0,
        alerting: false,
        created_at: "2022-06-26T12:48:33.440876Z",
        updated_at: "2022-06-26T12:54:32.177186Z",
        is_active: true,
        available: true,
        modifier_sets: [],
        images: [
          {
            id: 4069,
            variation: 17241,
            image,
            thumbnail_url,
            image_url,
            order: 0,
          },
        ],
        main_image_url,
        main_image_thumbnail_url,
      },
    ],
    main_image_thumbnail_url,
  },
  {
    id: 6216884,
    sku: null,
    unit: "number",
    priority: 100,
    super_resource: null,
    title: "کانسیلر میبلین فیت می",
    business: 1969986,
    description:
      "<p>کانسیلر فیت می&nbsp;میبلین بافت نرم و سبک این کانسیلر به راحتی روی پوست می نشیند و ظاهری طبیعی به آن می دهد</p><p><br></p><p>☆پوشش دهی مناسب</p><p>☆بدون ماسیده شدن روی پوست</p><p>☆مناسب برای پوشش لک و پف زیر چشم</p><p>☆پوشاننده ی حلقه های تیره و قرمزی های پوست</p><p>☆ضد حساسیت</p><p>☆فاقد چربی</p><p>☆بدون بو</p><p>☆حجم : 6.8 میل</p><p>☆ساخت کشور فرانسه</p>",
    labels: [568562, 568575, 574997],
    extra_data: {
      config: {
        is_saleable: true,
      },
      info_table: [],
      similar_products: {
        conjoined: false,
        categories: [568562],
      },
    },
    seo: {},
    multi_lang_data: {},
    is_active: true,
    variants_data: [],
    available: true,
    default_variation: {
      id: 17241,
      resource: 6216884,
      resource_type: "product",
      sku: null,
      title: "کانسیلر میبلین فیت می",
      images: [
        {
          id: 4069,
          variation: 17241,
          image,
          thumbnail_url,
          image_url,
          order: 0,
        },
      ],
      main_image_url,
      main_image_thumbnail_url,
      minimum_choice: null,
      maximum_choice: null,
      final_unit_cost: null,
      extra_data: {
        isSuper: false,
      },
      initial_price: 295000,
      discounted_price: 295000,
      packaging_price: 0,
      inventory_count: 0,
      keep_selling: true,
      threshold: 0,
      alerting: false,
      created_at: "2022-06-26T12:48:33.440876Z",
      updated_at: "2022-06-26T12:54:32.177186Z",
      is_active: true,
      available: true,
    },
    minimum_choice: null,
    maximum_choice: null,
    variations: [
      {
        id: 17241,
        resource: 6216884,
        resource_type: "product",
        sku: null,
        title: "کانسیلر میبلین فیت می",
        minimum_choice: null,
        maximum_choice: null,
        final_unit_cost: null,
        extra_data: {
          isSuper: false,
        },
        initial_price: 295000,
        discounted_price: 295000,
        packaging_price: 0,
        inventory_count: 0,
        keep_selling: true,
        threshold: 0,
        alerting: false,
        created_at: "2022-06-26T12:48:33.440876Z",
        updated_at: "2022-06-26T12:54:32.177186Z",
        is_active: true,
        available: true,
        modifier_sets: [],
        images: [
          {
            id: 4069,
            variation: 17241,
            image,
            thumbnail_url,
            image_url,
            order: 0,
          },
        ],
        main_image_url,
        main_image_thumbnail_url,
      },
    ],
    main_image_thumbnail_url,
  },
  {
    id: 6216884,
    sku: null,
    unit: "number",
    priority: 100,
    super_resource: null,
    title: "کانسیلر میبلین فیت می",
    business: 1969986,
    description:
      "<p>کانسیلر فیت می&nbsp;میبلین بافت نرم و سبک این کانسیلر به راحتی روی پوست می نشیند و ظاهری طبیعی به آن می دهد</p><p><br></p><p>☆پوشش دهی مناسب</p><p>☆بدون ماسیده شدن روی پوست</p><p>☆مناسب برای پوشش لک و پف زیر چشم</p><p>☆پوشاننده ی حلقه های تیره و قرمزی های پوست</p><p>☆ضد حساسیت</p><p>☆فاقد چربی</p><p>☆بدون بو</p><p>☆حجم : 6.8 میل</p><p>☆ساخت کشور فرانسه</p>",
    labels: [568562, 568575, 574997],
    extra_data: {
      config: {
        is_saleable: true,
      },
      info_table: [],
      similar_products: {
        conjoined: false,
        categories: [568562],
      },
    },
    seo: {},
    multi_lang_data: {},
    is_active: true,
    variants_data: [],
    available: true,
    default_variation: {
      id: 17241,
      resource: 6216884,
      resource_type: "product",
      sku: null,
      title: "کانسیلر میبلین فیت می",
      images: [
        {
          id: 4069,
          variation: 17241,
          image,
          thumbnail_url,
          image_url,
          order: 0,
        },
      ],
      main_image_url,
      main_image_thumbnail_url,
      minimum_choice: null,
      maximum_choice: null,
      final_unit_cost: null,
      extra_data: {
        isSuper: false,
      },
      initial_price: 295000,
      discounted_price: 295000,
      packaging_price: 0,
      inventory_count: 0,
      keep_selling: true,
      threshold: 0,
      alerting: false,
      created_at: "2022-06-26T12:48:33.440876Z",
      updated_at: "2022-06-26T12:54:32.177186Z",
      is_active: true,
      available: true,
    },
    minimum_choice: null,
    maximum_choice: null,
    variations: [
      {
        id: 17241,
        resource: 6216884,
        resource_type: "product",
        sku: null,
        title: "کانسیلر میبلین فیت می",
        minimum_choice: null,
        maximum_choice: null,
        final_unit_cost: null,
        extra_data: {
          isSuper: false,
        },
        initial_price: 295000,
        discounted_price: 295000,
        packaging_price: 0,
        inventory_count: 0,
        keep_selling: true,
        threshold: 0,
        alerting: false,
        created_at: "2022-06-26T12:48:33.440876Z",
        updated_at: "2022-06-26T12:54:32.177186Z",
        is_active: true,
        available: true,
        modifier_sets: [],
        images: [
          {
            id: 4069,
            variation: 17241,
            image,
            thumbnail_url,
            image_url,
            order: 0,
          },
        ],
        main_image_url,
        main_image_thumbnail_url,
      },
    ],
    main_image_thumbnail_url,
  },
  {
    id: 6216884,
    sku: null,
    unit: "number",
    priority: 100,
    super_resource: null,
    title: "کانسیلر میبلین فیت می",
    business: 1969986,
    description:
      "<p>کانسیلر فیت می&nbsp;میبلین بافت نرم و سبک این کانسیلر به راحتی روی پوست می نشیند و ظاهری طبیعی به آن می دهد</p><p><br></p><p>☆پوشش دهی مناسب</p><p>☆بدون ماسیده شدن روی پوست</p><p>☆مناسب برای پوشش لک و پف زیر چشم</p><p>☆پوشاننده ی حلقه های تیره و قرمزی های پوست</p><p>☆ضد حساسیت</p><p>☆فاقد چربی</p><p>☆بدون بو</p><p>☆حجم : 6.8 میل</p><p>☆ساخت کشور فرانسه</p>",
    labels: [568562, 568575, 574997],
    extra_data: {
      config: {
        is_saleable: true,
      },
      info_table: [],
      similar_products: {
        conjoined: false,
        categories: [568562],
      },
    },
    seo: {},
    multi_lang_data: {},
    is_active: true,
    variants_data: [],
    available: true,
    default_variation: {
      id: 17241,
      resource: 6216884,
      resource_type: "product",
      sku: null,
      title: "کانسیلر میبلین فیت می",
      images: [
        {
          id: 4069,
          variation: 17241,
          image,
          thumbnail_url,
          image_url,
          order: 0,
        },
      ],
      main_image_url,
      main_image_thumbnail_url,
      minimum_choice: null,
      maximum_choice: null,
      final_unit_cost: null,
      extra_data: {
        isSuper: false,
      },
      initial_price: 295000,
      discounted_price: 295000,
      packaging_price: 0,
      inventory_count: 0,
      keep_selling: true,
      threshold: 0,
      alerting: false,
      created_at: "2022-06-26T12:48:33.440876Z",
      updated_at: "2022-06-26T12:54:32.177186Z",
      is_active: true,
      available: true,
    },
    minimum_choice: null,
    maximum_choice: null,
    variations: [
      {
        id: 17241,
        resource: 6216884,
        resource_type: "product",
        sku: null,
        title: "کانسیلر میبلین فیت می",
        minimum_choice: null,
        maximum_choice: null,
        final_unit_cost: null,
        extra_data: {
          isSuper: false,
        },
        initial_price: 295000,
        discounted_price: 295000,
        packaging_price: 0,
        inventory_count: 0,
        keep_selling: true,
        threshold: 0,
        alerting: false,
        created_at: "2022-06-26T12:48:33.440876Z",
        updated_at: "2022-06-26T12:54:32.177186Z",
        is_active: true,
        available: true,
        modifier_sets: [],
        images: [
          {
            id: 4069,
            variation: 17241,
            image,
            thumbnail_url,
            image_url,
            order: 0,
          },
        ],
        main_image_url,
        main_image_thumbnail_url,
      },
    ],
    main_image_thumbnail_url,
  },
  {
    id: 6216884,
    sku: null,
    unit: "number",
    priority: 100,
    super_resource: null,
    title: "کانسیلر میبلین فیت می",
    business: 1969986,
    description:
      "<p>کانسیلر فیت می&nbsp;میبلین بافت نرم و سبک این کانسیلر به راحتی روی پوست می نشیند و ظاهری طبیعی به آن می دهد</p><p><br></p><p>☆پوشش دهی مناسب</p><p>☆بدون ماسیده شدن روی پوست</p><p>☆مناسب برای پوشش لک و پف زیر چشم</p><p>☆پوشاننده ی حلقه های تیره و قرمزی های پوست</p><p>☆ضد حساسیت</p><p>☆فاقد چربی</p><p>☆بدون بو</p><p>☆حجم : 6.8 میل</p><p>☆ساخت کشور فرانسه</p>",
    labels: [568562, 568575, 574997],
    extra_data: {
      config: {
        is_saleable: true,
      },
      info_table: [],
      similar_products: {
        conjoined: false,
        categories: [568562],
      },
    },
    seo: {},
    multi_lang_data: {},
    is_active: true,
    variants_data: [],
    available: true,
    default_variation: {
      id: 17241,
      resource: 6216884,
      resource_type: "product",
      sku: null,
      title: "کانسیلر میبلین فیت می",
      images: [
        {
          id: 4069,
          variation: 17241,
          image,
          thumbnail_url,
          image_url,
          order: 0,
        },
      ],
      main_image_url,
      main_image_thumbnail_url,
      minimum_choice: null,
      maximum_choice: null,
      final_unit_cost: null,
      extra_data: {
        isSuper: false,
      },
      initial_price: 295000,
      discounted_price: 295000,
      packaging_price: 0,
      inventory_count: 0,
      keep_selling: true,
      threshold: 0,
      alerting: false,
      created_at: "2022-06-26T12:48:33.440876Z",
      updated_at: "2022-06-26T12:54:32.177186Z",
      is_active: true,
      available: true,
    },
    minimum_choice: null,
    maximum_choice: null,
    variations: [
      {
        id: 17241,
        resource: 6216884,
        resource_type: "product",
        sku: null,
        title: "کانسیلر میبلین فیت می",
        minimum_choice: null,
        maximum_choice: null,
        final_unit_cost: null,
        extra_data: {
          isSuper: false,
        },
        initial_price: 295000,
        discounted_price: 295000,
        packaging_price: 0,
        inventory_count: 0,
        keep_selling: true,
        threshold: 0,
        alerting: false,
        created_at: "2022-06-26T12:48:33.440876Z",
        updated_at: "2022-06-26T12:54:32.177186Z",
        is_active: true,
        available: true,
        modifier_sets: [],
        images: [
          {
            id: 4069,
            variation: 17241,
            image,
            thumbnail_url,
            image_url,
            order: 0,
          },
        ],
        main_image_url,
        main_image_thumbnail_url,
      },
    ],
    main_image_thumbnail_url,
  },
  {
    id: 6216884,
    sku: null,
    unit: "number",
    priority: 100,
    super_resource: null,
    title: "کانسیلر میبلین فیت می",
    business: 1969986,
    description:
      "<p>کانسیلر فیت می&nbsp;میبلین بافت نرم و سبک این کانسیلر به راحتی روی پوست می نشیند و ظاهری طبیعی به آن می دهد</p><p><br></p><p>☆پوشش دهی مناسب</p><p>☆بدون ماسیده شدن روی پوست</p><p>☆مناسب برای پوشش لک و پف زیر چشم</p><p>☆پوشاننده ی حلقه های تیره و قرمزی های پوست</p><p>☆ضد حساسیت</p><p>☆فاقد چربی</p><p>☆بدون بو</p><p>☆حجم : 6.8 میل</p><p>☆ساخت کشور فرانسه</p>",
    labels: [568562, 568575, 574997],
    extra_data: {
      config: {
        is_saleable: true,
      },
      info_table: [],
      similar_products: {
        conjoined: false,
        categories: [568562],
      },
    },
    seo: {},
    multi_lang_data: {},
    is_active: true,
    variants_data: [],
    available: true,
    default_variation: {
      id: 17241,
      resource: 6216884,
      resource_type: "product",
      sku: null,
      title: "کانسیلر میبلین فیت می",
      images: [
        {
          id: 4069,
          variation: 17241,
          image,
          thumbnail_url,
          image_url,
          order: 0,
        },
      ],
      main_image_url,
      main_image_thumbnail_url,
      minimum_choice: null,
      maximum_choice: null,
      final_unit_cost: null,
      extra_data: {
        isSuper: false,
      },
      initial_price: 295000,
      discounted_price: 295000,
      packaging_price: 0,
      inventory_count: 0,
      keep_selling: true,
      threshold: 0,
      alerting: false,
      created_at: "2022-06-26T12:48:33.440876Z",
      updated_at: "2022-06-26T12:54:32.177186Z",
      is_active: true,
      available: true,
    },
    minimum_choice: null,
    maximum_choice: null,
    variations: [
      {
        id: 17241,
        resource: 6216884,
        resource_type: "product",
        sku: null,
        title: "کانسیلر میبلین فیت می",
        minimum_choice: null,
        maximum_choice: null,
        final_unit_cost: null,
        extra_data: {
          isSuper: false,
        },
        initial_price: 295000,
        discounted_price: 295000,
        packaging_price: 0,
        inventory_count: 0,
        keep_selling: true,
        threshold: 0,
        alerting: false,
        created_at: "2022-06-26T12:48:33.440876Z",
        updated_at: "2022-06-26T12:54:32.177186Z",
        is_active: true,
        available: true,
        modifier_sets: [],
        images: [
          {
            id: 4069,
            variation: 17241,
            image,
            thumbnail_url,
            image_url,
            order: 0,
          },
        ],
        main_image_url,
        main_image_thumbnail_url,
      },
    ],
    main_image_thumbnail_url,
  },
  {
    id: 6216884,
    sku: null,
    unit: "number",
    priority: 100,
    super_resource: null,
    title: "کانسیلر میبلین فیت می",
    business: 1969986,
    description:
      "<p>کانسیلر فیت می&nbsp;میبلین بافت نرم و سبک این کانسیلر به راحتی روی پوست می نشیند و ظاهری طبیعی به آن می دهد</p><p><br></p><p>☆پوشش دهی مناسب</p><p>☆بدون ماسیده شدن روی پوست</p><p>☆مناسب برای پوشش لک و پف زیر چشم</p><p>☆پوشاننده ی حلقه های تیره و قرمزی های پوست</p><p>☆ضد حساسیت</p><p>☆فاقد چربی</p><p>☆بدون بو</p><p>☆حجم : 6.8 میل</p><p>☆ساخت کشور فرانسه</p>",
    labels: [568562, 568575, 574997],
    extra_data: {
      config: {
        is_saleable: true,
      },
      info_table: [],
      similar_products: {
        conjoined: false,
        categories: [568562],
      },
    },
    seo: {},
    multi_lang_data: {},
    is_active: true,
    variants_data: [],
    available: true,
    default_variation: {
      id: 17241,
      resource: 6216884,
      resource_type: "product",
      sku: null,
      title: "کانسیلر میبلین فیت می",
      images: [
        {
          id: 4069,
          variation: 17241,
          image,
          thumbnail_url,
          image_url,
          order: 0,
        },
      ],
      main_image_url,
      main_image_thumbnail_url,
      minimum_choice: null,
      maximum_choice: null,
      final_unit_cost: null,
      extra_data: {
        isSuper: false,
      },
      initial_price: 295000,
      discounted_price: 295000,
      packaging_price: 0,
      inventory_count: 0,
      keep_selling: true,
      threshold: 0,
      alerting: false,
      created_at: "2022-06-26T12:48:33.440876Z",
      updated_at: "2022-06-26T12:54:32.177186Z",
      is_active: true,
      available: true,
    },
    minimum_choice: null,
    maximum_choice: null,
    variations: [
      {
        id: 17241,
        resource: 6216884,
        resource_type: "product",
        sku: null,
        title: "کانسیلر میبلین فیت می",
        minimum_choice: null,
        maximum_choice: null,
        final_unit_cost: null,
        extra_data: {
          isSuper: false,
        },
        initial_price: 295000,
        discounted_price: 295000,
        packaging_price: 0,
        inventory_count: 0,
        keep_selling: true,
        threshold: 0,
        alerting: false,
        created_at: "2022-06-26T12:48:33.440876Z",
        updated_at: "2022-06-26T12:54:32.177186Z",
        is_active: true,
        available: true,
        modifier_sets: [],
        images: [
          {
            id: 4069,
            variation: 17241,
            image,
            thumbnail_url,
            image_url,
            order: 0,
          },
        ],
        main_image_url,
        main_image_thumbnail_url,
      },
    ],
    main_image_thumbnail_url,
  },
  {
    id: 6216884,
    sku: null,
    unit: "number",
    priority: 100,
    super_resource: null,
    title: "کانسیلر میبلین فیت می",
    business: 1969986,
    description:
      "<p>کانسیلر فیت می&nbsp;میبلین بافت نرم و سبک این کانسیلر به راحتی روی پوست می نشیند و ظاهری طبیعی به آن می دهد</p><p><br></p><p>☆پوشش دهی مناسب</p><p>☆بدون ماسیده شدن روی پوست</p><p>☆مناسب برای پوشش لک و پف زیر چشم</p><p>☆پوشاننده ی حلقه های تیره و قرمزی های پوست</p><p>☆ضد حساسیت</p><p>☆فاقد چربی</p><p>☆بدون بو</p><p>☆حجم : 6.8 میل</p><p>☆ساخت کشور فرانسه</p>",
    labels: [568562, 568575, 574997],
    extra_data: {
      config: {
        is_saleable: true,
      },
      info_table: [],
      similar_products: {
        conjoined: false,
        categories: [568562],
      },
    },
    seo: {},
    multi_lang_data: {},
    is_active: true,
    variants_data: [],
    available: true,
    default_variation: {
      id: 17241,
      resource: 6216884,
      resource_type: "product",
      sku: null,
      title: "کانسیلر میبلین فیت می",
      images: [
        {
          id: 4069,
          variation: 17241,
          image,
          thumbnail_url,
          image_url,
          order: 0,
        },
      ],
      main_image_url,
      main_image_thumbnail_url,
      minimum_choice: null,
      maximum_choice: null,
      final_unit_cost: null,
      extra_data: {
        isSuper: false,
      },
      initial_price: 295000,
      discounted_price: 295000,
      packaging_price: 0,
      inventory_count: 0,
      keep_selling: true,
      threshold: 0,
      alerting: false,
      created_at: "2022-06-26T12:48:33.440876Z",
      updated_at: "2022-06-26T12:54:32.177186Z",
      is_active: true,
      available: true,
    },
    minimum_choice: null,
    maximum_choice: null,
    variations: [
      {
        id: 17241,
        resource: 6216884,
        resource_type: "product",
        sku: null,
        title: "کانسیلر میبلین فیت می",
        minimum_choice: null,
        maximum_choice: null,
        final_unit_cost: null,
        extra_data: {
          isSuper: false,
        },
        initial_price: 295000,
        discounted_price: 295000,
        packaging_price: 0,
        inventory_count: 0,
        keep_selling: true,
        threshold: 0,
        alerting: false,
        created_at: "2022-06-26T12:48:33.440876Z",
        updated_at: "2022-06-26T12:54:32.177186Z",
        is_active: true,
        available: true,
        modifier_sets: [],
        images: [
          {
            id: 4069,
            variation: 17241,
            image,
            thumbnail_url,
            image_url,
            order: 0,
          },
        ],
        main_image_url,
        main_image_thumbnail_url,
      },
    ],
    main_image_thumbnail_url,
  },
  {
    id: 6216884,
    sku: null,
    unit: "number",
    priority: 100,
    super_resource: null,
    title: "کانسیلر میبلین فیت می",
    business: 1969986,
    description:
      "<p>کانسیلر فیت می&nbsp;میبلین بافت نرم و سبک این کانسیلر به راحتی روی پوست می نشیند و ظاهری طبیعی به آن می دهد</p><p><br></p><p>☆پوشش دهی مناسب</p><p>☆بدون ماسیده شدن روی پوست</p><p>☆مناسب برای پوشش لک و پف زیر چشم</p><p>☆پوشاننده ی حلقه های تیره و قرمزی های پوست</p><p>☆ضد حساسیت</p><p>☆فاقد چربی</p><p>☆بدون بو</p><p>☆حجم : 6.8 میل</p><p>☆ساخت کشور فرانسه</p>",
    labels: [568562, 568575, 574997],
    extra_data: {
      config: {
        is_saleable: true,
      },
      info_table: [],
      similar_products: {
        conjoined: false,
        categories: [568562],
      },
    },
    seo: {},
    multi_lang_data: {},
    is_active: true,
    variants_data: [],
    available: true,
    default_variation: {
      id: 17241,
      resource: 6216884,
      resource_type: "product",
      sku: null,
      title: "کانسیلر میبلین فیت می",
      images: [
        {
          id: 4069,
          variation: 17241,
          image,
          thumbnail_url,
          image_url,
          order: 0,
        },
      ],
      main_image_url,
      main_image_thumbnail_url,
      minimum_choice: null,
      maximum_choice: null,
      final_unit_cost: null,
      extra_data: {
        isSuper: false,
      },
      initial_price: 295000,
      discounted_price: 295000,
      packaging_price: 0,
      inventory_count: 0,
      keep_selling: true,
      threshold: 0,
      alerting: false,
      created_at: "2022-06-26T12:48:33.440876Z",
      updated_at: "2022-06-26T12:54:32.177186Z",
      is_active: true,
      available: true,
    },
    minimum_choice: null,
    maximum_choice: null,
    variations: [
      {
        id: 17241,
        resource: 6216884,
        resource_type: "product",
        sku: null,
        title: "کانسیلر میبلین فیت می",
        minimum_choice: null,
        maximum_choice: null,
        final_unit_cost: null,
        extra_data: {
          isSuper: false,
        },
        initial_price: 295000,
        discounted_price: 295000,
        packaging_price: 0,
        inventory_count: 0,
        keep_selling: true,
        threshold: 0,
        alerting: false,
        created_at: "2022-06-26T12:48:33.440876Z",
        updated_at: "2022-06-26T12:54:32.177186Z",
        is_active: true,
        available: true,
        modifier_sets: [],
        images: [
          {
            id: 4069,
            variation: 17241,
            image,
            thumbnail_url,
            image_url,
            order: 0,
          },
        ],
        main_image_url,
        main_image_thumbnail_url,
      },
    ],
    main_image_thumbnail_url,
  },
  {
    id: 6216884,
    sku: null,
    unit: "number",
    priority: 100,
    super_resource: null,
    title: "کانسیلر میبلین فیت می",
    business: 1969986,
    description:
      "<p>کانسیلر فیت می&nbsp;میبلین بافت نرم و سبک این کانسیلر به راحتی روی پوست می نشیند و ظاهری طبیعی به آن می دهد</p><p><br></p><p>☆پوشش دهی مناسب</p><p>☆بدون ماسیده شدن روی پوست</p><p>☆مناسب برای پوشش لک و پف زیر چشم</p><p>☆پوشاننده ی حلقه های تیره و قرمزی های پوست</p><p>☆ضد حساسیت</p><p>☆فاقد چربی</p><p>☆بدون بو</p><p>☆حجم : 6.8 میل</p><p>☆ساخت کشور فرانسه</p>",
    labels: [568562, 568575, 574997],
    extra_data: {
      config: {
        is_saleable: true,
      },
      info_table: [],
      similar_products: {
        conjoined: false,
        categories: [568562],
      },
    },
    seo: {},
    multi_lang_data: {},
    is_active: true,
    variants_data: [],
    available: true,
    default_variation: {
      id: 17241,
      resource: 6216884,
      resource_type: "product",
      sku: null,
      title: "کانسیلر میبلین فیت می",
      images: [
        {
          id: 4069,
          variation: 17241,
          image,
          thumbnail_url,
          image_url,
          order: 0,
        },
      ],
      main_image_url,
      main_image_thumbnail_url,
      minimum_choice: null,
      maximum_choice: null,
      final_unit_cost: null,
      extra_data: {
        isSuper: false,
      },
      initial_price: 295000,
      discounted_price: 295000,
      packaging_price: 0,
      inventory_count: 0,
      keep_selling: true,
      threshold: 0,
      alerting: false,
      created_at: "2022-06-26T12:48:33.440876Z",
      updated_at: "2022-06-26T12:54:32.177186Z",
      is_active: true,
      available: true,
    },
    minimum_choice: null,
    maximum_choice: null,
    variations: [
      {
        id: 17241,
        resource: 6216884,
        resource_type: "product",
        sku: null,
        title: "کانسیلر میبلین فیت می",
        minimum_choice: null,
        maximum_choice: null,
        final_unit_cost: null,
        extra_data: {
          isSuper: false,
        },
        initial_price: 295000,
        discounted_price: 295000,
        packaging_price: 0,
        inventory_count: 0,
        keep_selling: true,
        threshold: 0,
        alerting: false,
        created_at: "2022-06-26T12:48:33.440876Z",
        updated_at: "2022-06-26T12:54:32.177186Z",
        is_active: true,
        available: true,
        modifier_sets: [],
        images: [
          {
            id: 4069,
            variation: 17241,
            image,
            thumbnail_url,
            image_url,
            order: 0,
          },
        ],
        main_image_url,
        main_image_thumbnail_url,
      },
    ],
    main_image_thumbnail_url,
  },
  {
    id: 6216884,
    sku: null,
    unit: "number",
    priority: 100,
    super_resource: null,
    title: "کانسیلر میبلین فیت می",
    business: 1969986,
    description:
      "<p>کانسیلر فیت می&nbsp;میبلین بافت نرم و سبک این کانسیلر به راحتی روی پوست می نشیند و ظاهری طبیعی به آن می دهد</p><p><br></p><p>☆پوشش دهی مناسب</p><p>☆بدون ماسیده شدن روی پوست</p><p>☆مناسب برای پوشش لک و پف زیر چشم</p><p>☆پوشاننده ی حلقه های تیره و قرمزی های پوست</p><p>☆ضد حساسیت</p><p>☆فاقد چربی</p><p>☆بدون بو</p><p>☆حجم : 6.8 میل</p><p>☆ساخت کشور فرانسه</p>",
    labels: [568562, 568575, 574997],
    extra_data: {
      config: {
        is_saleable: true,
      },
      info_table: [],
      similar_products: {
        conjoined: false,
        categories: [568562],
      },
    },
    seo: {},
    multi_lang_data: {},
    is_active: true,
    variants_data: [],
    available: true,
    default_variation: {
      id: 17241,
      resource: 6216884,
      resource_type: "product",
      sku: null,
      title: "کانسیلر میبلین فیت می",
      images: [
        {
          id: 4069,
          variation: 17241,
          image,
          thumbnail_url,
          image_url,
          order: 0,
        },
      ],
      main_image_url,
      main_image_thumbnail_url,
      minimum_choice: null,
      maximum_choice: null,
      final_unit_cost: null,
      extra_data: {
        isSuper: false,
      },
      initial_price: 295000,
      discounted_price: 295000,
      packaging_price: 0,
      inventory_count: 0,
      keep_selling: true,
      threshold: 0,
      alerting: false,
      created_at: "2022-06-26T12:48:33.440876Z",
      updated_at: "2022-06-26T12:54:32.177186Z",
      is_active: true,
      available: true,
    },
    minimum_choice: null,
    maximum_choice: null,
    variations: [
      {
        id: 17241,
        resource: 6216884,
        resource_type: "product",
        sku: null,
        title: "کانسیلر میبلین فیت می",
        minimum_choice: null,
        maximum_choice: null,
        final_unit_cost: null,
        extra_data: {
          isSuper: false,
        },
        initial_price: 295000,
        discounted_price: 295000,
        packaging_price: 0,
        inventory_count: 0,
        keep_selling: true,
        threshold: 0,
        alerting: false,
        created_at: "2022-06-26T12:48:33.440876Z",
        updated_at: "2022-06-26T12:54:32.177186Z",
        is_active: true,
        available: true,
        modifier_sets: [],
        images: [
          {
            id: 4069,
            variation: 17241,
            image,
            thumbnail_url,
            image_url,
            order: 0,
          },
        ],
        main_image_url,
        main_image_thumbnail_url,
      },
    ],
    main_image_thumbnail_url,
  },
  {
    id: 6216884,
    sku: null,
    unit: "number",
    priority: 100,
    super_resource: null,
    title: "کانسیلر میبلین فیت می",
    business: 1969986,
    description:
      "<p>کانسیلر فیت می&nbsp;میبلین بافت نرم و سبک این کانسیلر به راحتی روی پوست می نشیند و ظاهری طبیعی به آن می دهد</p><p><br></p><p>☆پوشش دهی مناسب</p><p>☆بدون ماسیده شدن روی پوست</p><p>☆مناسب برای پوشش لک و پف زیر چشم</p><p>☆پوشاننده ی حلقه های تیره و قرمزی های پوست</p><p>☆ضد حساسیت</p><p>☆فاقد چربی</p><p>☆بدون بو</p><p>☆حجم : 6.8 میل</p><p>☆ساخت کشور فرانسه</p>",
    labels: [568562, 568575, 574997],
    extra_data: {
      config: {
        is_saleable: true,
      },
      info_table: [],
      similar_products: {
        conjoined: false,
        categories: [568562],
      },
    },
    seo: {},
    multi_lang_data: {},
    is_active: true,
    variants_data: [],
    available: true,
    default_variation: {
      id: 17241,
      resource: 6216884,
      resource_type: "product",
      sku: null,
      title: "کانسیلر میبلین فیت می",
      images: [
        {
          id: 4069,
          variation: 17241,
          image,
          thumbnail_url,
          image_url,
          order: 0,
        },
      ],
      main_image_url,
      main_image_thumbnail_url,
      minimum_choice: null,
      maximum_choice: null,
      final_unit_cost: null,
      extra_data: {
        isSuper: false,
      },
      initial_price: 295000,
      discounted_price: 295000,
      packaging_price: 0,
      inventory_count: 0,
      keep_selling: true,
      threshold: 0,
      alerting: false,
      created_at: "2022-06-26T12:48:33.440876Z",
      updated_at: "2022-06-26T12:54:32.177186Z",
      is_active: true,
      available: true,
    },
    minimum_choice: null,
    maximum_choice: null,
    variations: [
      {
        id: 17241,
        resource: 6216884,
        resource_type: "product",
        sku: null,
        title: "کانسیلر میبلین فیت می",
        minimum_choice: null,
        maximum_choice: null,
        final_unit_cost: null,
        extra_data: {
          isSuper: false,
        },
        initial_price: 295000,
        discounted_price: 295000,
        packaging_price: 0,
        inventory_count: 0,
        keep_selling: true,
        threshold: 0,
        alerting: false,
        created_at: "2022-06-26T12:48:33.440876Z",
        updated_at: "2022-06-26T12:54:32.177186Z",
        is_active: true,
        available: true,
        modifier_sets: [],
        images: [
          {
            id: 4069,
            variation: 17241,
            image,
            thumbnail_url,
            image_url,
            order: 0,
          },
        ],
        main_image_url,
        main_image_thumbnail_url,
      },
    ],
    main_image_thumbnail_url,
  },
  {
    id: 6216884,
    sku: null,
    unit: "number",
    priority: 100,
    super_resource: null,
    title: "کانسیلر میبلین فیت می",
    business: 1969986,
    description:
      "<p>کانسیلر فیت می&nbsp;میبلین بافت نرم و سبک این کانسیلر به راحتی روی پوست می نشیند و ظاهری طبیعی به آن می دهد</p><p><br></p><p>☆پوشش دهی مناسب</p><p>☆بدون ماسیده شدن روی پوست</p><p>☆مناسب برای پوشش لک و پف زیر چشم</p><p>☆پوشاننده ی حلقه های تیره و قرمزی های پوست</p><p>☆ضد حساسیت</p><p>☆فاقد چربی</p><p>☆بدون بو</p><p>☆حجم : 6.8 میل</p><p>☆ساخت کشور فرانسه</p>",
    labels: [568562, 568575, 574997],
    extra_data: {
      config: {
        is_saleable: true,
      },
      info_table: [],
      similar_products: {
        conjoined: false,
        categories: [568562],
      },
    },
    seo: {},
    multi_lang_data: {},
    is_active: true,
    variants_data: [],
    available: true,
    default_variation: {
      id: 17241,
      resource: 6216884,
      resource_type: "product",
      sku: null,
      title: "کانسیلر میبلین فیت می",
      images: [
        {
          id: 4069,
          variation: 17241,
          image,
          thumbnail_url,
          image_url,
          order: 0,
        },
      ],
      main_image_url,
      main_image_thumbnail_url,
      minimum_choice: null,
      maximum_choice: null,
      final_unit_cost: null,
      extra_data: {
        isSuper: false,
      },
      initial_price: 295000,
      discounted_price: 295000,
      packaging_price: 0,
      inventory_count: 0,
      keep_selling: true,
      threshold: 0,
      alerting: false,
      created_at: "2022-06-26T12:48:33.440876Z",
      updated_at: "2022-06-26T12:54:32.177186Z",
      is_active: true,
      available: true,
    },
    minimum_choice: null,
    maximum_choice: null,
    variations: [
      {
        id: 17241,
        resource: 6216884,
        resource_type: "product",
        sku: null,
        title: "کانسیلر میبلین فیت می",
        minimum_choice: null,
        maximum_choice: null,
        final_unit_cost: null,
        extra_data: {
          isSuper: false,
        },
        initial_price: 295000,
        discounted_price: 295000,
        packaging_price: 0,
        inventory_count: 0,
        keep_selling: true,
        threshold: 0,
        alerting: false,
        created_at: "2022-06-26T12:48:33.440876Z",
        updated_at: "2022-06-26T12:54:32.177186Z",
        is_active: true,
        available: true,
        modifier_sets: [],
        images: [
          {
            id: 4069,
            variation: 17241,
            image,
            thumbnail_url,
            image_url,
            order: 0,
          },
        ],
        main_image_url,
        main_image_thumbnail_url,
      },
    ],
    main_image_thumbnail_url,
  },
  {
    id: 6216884,
    sku: null,
    unit: "number",
    priority: 100,
    super_resource: null,
    title: "کانسیلر میبلین فیت می",
    business: 1969986,
    description:
      "<p>کانسیلر فیت می&nbsp;میبلین بافت نرم و سبک این کانسیلر به راحتی روی پوست می نشیند و ظاهری طبیعی به آن می دهد</p><p><br></p><p>☆پوشش دهی مناسب</p><p>☆بدون ماسیده شدن روی پوست</p><p>☆مناسب برای پوشش لک و پف زیر چشم</p><p>☆پوشاننده ی حلقه های تیره و قرمزی های پوست</p><p>☆ضد حساسیت</p><p>☆فاقد چربی</p><p>☆بدون بو</p><p>☆حجم : 6.8 میل</p><p>☆ساخت کشور فرانسه</p>",
    labels: [568562, 568575, 574997],
    extra_data: {
      config: {
        is_saleable: true,
      },
      info_table: [],
      similar_products: {
        conjoined: false,
        categories: [568562],
      },
    },
    seo: {},
    multi_lang_data: {},
    is_active: true,
    variants_data: [],
    available: true,
    default_variation: {
      id: 17241,
      resource: 6216884,
      resource_type: "product",
      sku: null,
      title: "کانسیلر میبلین فیت می",
      images: [
        {
          id: 4069,
          variation: 17241,
          image,
          thumbnail_url,
          image_url,
          order: 0,
        },
      ],
      main_image_url,
      main_image_thumbnail_url,
      minimum_choice: null,
      maximum_choice: null,
      final_unit_cost: null,
      extra_data: {
        isSuper: false,
      },
      initial_price: 295000,
      discounted_price: 295000,
      packaging_price: 0,
      inventory_count: 0,
      keep_selling: true,
      threshold: 0,
      alerting: false,
      created_at: "2022-06-26T12:48:33.440876Z",
      updated_at: "2022-06-26T12:54:32.177186Z",
      is_active: true,
      available: true,
    },
    minimum_choice: null,
    maximum_choice: null,
    variations: [
      {
        id: 17241,
        resource: 6216884,
        resource_type: "product",
        sku: null,
        title: "کانسیلر میبلین فیت می",
        minimum_choice: null,
        maximum_choice: null,
        final_unit_cost: null,
        extra_data: {
          isSuper: false,
        },
        initial_price: 295000,
        discounted_price: 295000,
        packaging_price: 0,
        inventory_count: 0,
        keep_selling: true,
        threshold: 0,
        alerting: false,
        created_at: "2022-06-26T12:48:33.440876Z",
        updated_at: "2022-06-26T12:54:32.177186Z",
        is_active: true,
        available: true,
        modifier_sets: [],
        images: [
          {
            id: 4069,
            variation: 17241,
            image,
            thumbnail_url,
            image_url,
            order: 0,
          },
        ],
        main_image_url,
        main_image_thumbnail_url,
      },
    ],
    main_image_thumbnail_url,
  },
  {
    id: 6216884,
    sku: null,
    unit: "number",
    priority: 100,
    super_resource: null,
    title: "کانسیلر میبلین فیت می",
    business: 1969986,
    description:
      "<p>کانسیلر فیت می&nbsp;میبلین بافت نرم و سبک این کانسیلر به راحتی روی پوست می نشیند و ظاهری طبیعی به آن می دهد</p><p><br></p><p>☆پوشش دهی مناسب</p><p>☆بدون ماسیده شدن روی پوست</p><p>☆مناسب برای پوشش لک و پف زیر چشم</p><p>☆پوشاننده ی حلقه های تیره و قرمزی های پوست</p><p>☆ضد حساسیت</p><p>☆فاقد چربی</p><p>☆بدون بو</p><p>☆حجم : 6.8 میل</p><p>☆ساخت کشور فرانسه</p>",
    labels: [568562, 568575, 574997],
    extra_data: {
      config: {
        is_saleable: true,
      },
      info_table: [],
      similar_products: {
        conjoined: false,
        categories: [568562],
      },
    },
    seo: {},
    multi_lang_data: {},
    is_active: true,
    variants_data: [],
    available: true,
    default_variation: {
      id: 17241,
      resource: 6216884,
      resource_type: "product",
      sku: null,
      title: "کانسیلر میبلین فیت می",
      images: [
        {
          id: 4069,
          variation: 17241,
          image,
          thumbnail_url,
          image_url,
          order: 0,
        },
      ],
      main_image_url,
      main_image_thumbnail_url,
      minimum_choice: null,
      maximum_choice: null,
      final_unit_cost: null,
      extra_data: {
        isSuper: false,
      },
      initial_price: 295000,
      discounted_price: 295000,
      packaging_price: 0,
      inventory_count: 0,
      keep_selling: true,
      threshold: 0,
      alerting: false,
      created_at: "2022-06-26T12:48:33.440876Z",
      updated_at: "2022-06-26T12:54:32.177186Z",
      is_active: true,
      available: true,
    },
    minimum_choice: null,
    maximum_choice: null,
    variations: [
      {
        id: 17241,
        resource: 6216884,
        resource_type: "product",
        sku: null,
        title: "کانسیلر میبلین فیت می",
        minimum_choice: null,
        maximum_choice: null,
        final_unit_cost: null,
        extra_data: {
          isSuper: false,
        },
        initial_price: 295000,
        discounted_price: 295000,
        packaging_price: 0,
        inventory_count: 0,
        keep_selling: true,
        threshold: 0,
        alerting: false,
        created_at: "2022-06-26T12:48:33.440876Z",
        updated_at: "2022-06-26T12:54:32.177186Z",
        is_active: true,
        available: true,
        modifier_sets: [],
        images: [
          {
            id: 4069,
            variation: 17241,
            image,
            thumbnail_url,
            image_url,
            order: 0,
          },
        ],
        main_image_url,
        main_image_thumbnail_url,
      },
    ],
    main_image_thumbnail_url,
  },
  {
    id: 6216884,
    sku: null,
    unit: "number",
    priority: 100,
    super_resource: null,
    title: "کانسیلر میبلین فیت می",
    business: 1969986,
    description:
      "<p>کانسیلر فیت می&nbsp;میبلین بافت نرم و سبک این کانسیلر به راحتی روی پوست می نشیند و ظاهری طبیعی به آن می دهد</p><p><br></p><p>☆پوشش دهی مناسب</p><p>☆بدون ماسیده شدن روی پوست</p><p>☆مناسب برای پوشش لک و پف زیر چشم</p><p>☆پوشاننده ی حلقه های تیره و قرمزی های پوست</p><p>☆ضد حساسیت</p><p>☆فاقد چربی</p><p>☆بدون بو</p><p>☆حجم : 6.8 میل</p><p>☆ساخت کشور فرانسه</p>",
    labels: [568562, 568575, 574997],
    extra_data: {
      config: {
        is_saleable: true,
      },
      info_table: [],
      similar_products: {
        conjoined: false,
        categories: [568562],
      },
    },
    seo: {},
    multi_lang_data: {},
    is_active: true,
    variants_data: [],
    available: true,
    default_variation: {
      id: 17241,
      resource: 6216884,
      resource_type: "product",
      sku: null,
      title: "کانسیلر میبلین فیت می",
      images: [
        {
          id: 4069,
          variation: 17241,
          image,
          thumbnail_url,
          image_url,
          order: 0,
        },
      ],
      main_image_url,
      main_image_thumbnail_url,
      minimum_choice: null,
      maximum_choice: null,
      final_unit_cost: null,
      extra_data: {
        isSuper: false,
      },
      initial_price: 295000,
      discounted_price: 295000,
      packaging_price: 0,
      inventory_count: 0,
      keep_selling: true,
      threshold: 0,
      alerting: false,
      created_at: "2022-06-26T12:48:33.440876Z",
      updated_at: "2022-06-26T12:54:32.177186Z",
      is_active: true,
      available: true,
    },
    minimum_choice: null,
    maximum_choice: null,
    variations: [
      {
        id: 17241,
        resource: 6216884,
        resource_type: "product",
        sku: null,
        title: "کانسیلر میبلین فیت می",
        minimum_choice: null,
        maximum_choice: null,
        final_unit_cost: null,
        extra_data: {
          isSuper: false,
        },
        initial_price: 295000,
        discounted_price: 295000,
        packaging_price: 0,
        inventory_count: 0,
        keep_selling: true,
        threshold: 0,
        alerting: false,
        created_at: "2022-06-26T12:48:33.440876Z",
        updated_at: "2022-06-26T12:54:32.177186Z",
        is_active: true,
        available: true,
        modifier_sets: [],
        images: [
          {
            id: 4069,
            variation: 17241,
            image,
            thumbnail_url,
            image_url,
            order: 0,
          },
        ],
        main_image_url,
        main_image_thumbnail_url,
      },
    ],
    main_image_thumbnail_url,
  },
];

export const PREPARATION_TIME_BY_DAY = "day";
export const PREPARATION_TIME_BY_HOUR = "hour";
export const PREPARATION_TIME_BY_MINUTE = "minute";
