import uniqueId from "lodash/uniqueId";

export const example_businesses = [
  {
    title: "رستوران و کافی شاپ",
    label: "restaurant_and_coffee",
    id: uniqueId(),
    items: [
      {
        id: uniqueId(),
        image: "/images/2-1-cleanfood.jpg",
        name: "کلین فود",
        alt: "سایت کلین فود - طراحی شده با ویترین",
        link: "https://cleanfoods.ir/",
      },
      {
        id: uniqueId(),
        image: "/images/2-2-ashdarchin.jpg",
        name: " آشکده دارچین",
        alt: "سایت آشکده دارچین - طراحی شده با ویترین",
        link: "https://ashdarchin.com/",
      },
      {
        id: uniqueId(),
        image: "/images/2-5-tarighatshariati.jpg",
        name: "رستوران طریقت (شریعتی)",
        alt: "سایت رستوران طریقت (شریعتی) - طراحی شده با ویترین",
        link: "https://tarighatshariati.com/",
      },
      {
        id: uniqueId(),
        image: "/images/2-4-gilane.jpg",
        name: "رستوران گیلانه",
        alt: "سایت گیلانه - طراحی شده با ویترین",
        link: "https://gilaneh-restaurant.ir/",
      },
      {
        id: uniqueId(),
        image: "/images/2-7-chopchop.jpg",
        name: "رستوران چاپ چاپ",
        alt: "سایت رستوران چاپ چاپ - طراحی شده با ویترین",
        link: "https://chopchopasia.com/",
      },
      {
        id: uniqueId(),
        image: "/images/2-8-bambooexpress.jpg",
        name: " بامبو اکسپرس",
        alt: "سایت بامبو اکسپرس - طراحی شده با ویترین",
        link: "https://bambooexp.com/",
      },
      {
        id: uniqueId(),
        image: "/images/1-7-addressfoodhall.png",
        name: " آدرس فود هال",
        alt: "منوی دیجیتال آدرس فود هال - طراحی شده با ویترین",
        link: "https://addressfoodhall.ir.ink/menu",
      },
      {
        id: uniqueId(),
        image: "/images/2-3-sarzaminsookhari.jpg",
        name: "سرزمین سوخاری",
        alt: "سایت سرزمین سوخاری - طراحی شده با ویترین",
        link: "https://sarzaminesookhari.com/",
      },
      {
        id: uniqueId(),
        image: "/images/2-6-river.jpg",
        name: "رستوران ایتالیایی ریور",
        alt: "سایت رستوران ایتالیایی ریور - طراحی شده با ویترین",
        link: "https://river-restaurant.com/",
      },
      {
        id: uniqueId(),
        image: "/images/3-1-raees.jpg",
        name: "کافه رئیس",
        alt: "فروشگاه کافه رئیس - طراحی شده با ویترین",
        link: "https://raees.shop",
      },
      {
        id: uniqueId(),
        image: "/images/3-2-manza.jpg",
        name: "کافه مان‌زا",
        alt: "سایت کافه مان‌زا - طراحی شده با ویترین",
        link: "https://manzacafe.com/",
      },
    ],
  },
  {
    id: uniqueId(),
    label: "digital",
    title: "ابزار و صنعت",
    items: [
      {
        id: uniqueId(),
        image: "/images/1-3-asuabzar.jpg",
        name: "آسو ابزار",
        alt: "سایت آسو ابزار - طراحی شده با ویترین",
        link: "https://asuabzar.com/",
      },
      {
        id: uniqueId(),
        image: "/images/1-5-abzaroxin.jpg",
        name: "ابزار اکسین",
        link: "https://abzaroxin.com/",
        alt: "سایت ابزار اکسین - طراحی شده با ویترین",
      },
      {
        id: uniqueId(),
        image: "/images/1-2-mototot.jpg",
        name: "تات سیکلت",
        alt: "سایت تات سیکلت - طراحی شده با ویترین",
        link: "https://mototat.ir.ink/",
      },
      {
        id: uniqueId(),
        image: "/images/11-2-momtaz.jpg",
        name: "صنایع ممتاز",
        alt: "سایت صنایع ممتاز - طراحی شده با ویترین",
        link: "https://sanayemomtaz.com",
      },
    ],
  },
  {
    id: uniqueId(),
    label: "digital",
    title: "لوازم دیجیتال",
    logo: "/images/DigitalGoods.png",
    items: [
      {
        id: uniqueId(),
        image: "/images/3-1-imc.jpg",
        name: " فروشگاه آنلاین IMC",
        alt: "سایت فروشگاه آنلاین IMC - طراحی شده با ویترین",
        link: "https://imc.ir/",
      },
      {
        id: uniqueId(),
        image: "/images/3-2-mahan.jpg",
        name: "موبایل ماهان",
        link: "https://30moj.com/",
        alt: "سایت موبایل ماهان - طراحی شده با ویترین",
      },
      {
        id: uniqueId(),
        image: "/images/3-3-onlineroshan.jpg",
        name: "فروشگاه آنلاین روشن",
        alt: "سایت فروشگاه آنلاین روشن - طراحی شده با ویترین",
        link: "https://r-market.ir/",
      },
      {
        id: uniqueId(),
        image: "/images/3-4-fadak.jpg",
        name: "فروشگاه فدک",
        alt: "سایت فروشگاه فدک - طراحی شده با ویترین",
        link: "https://fadakst.ir/",
      },
    ],
  },
  {
    id: uniqueId(),
    label: "foodstuffs",
    title: "مواد غذایی",
    items: [
      {
        id: uniqueId(),
        image: "/images/1-8-payedigesadat.jpg",
        name: "پای دیگ سادات",
        alt: "سایت پای دیگ سادات - طراحی شده با ویترین",
        link: "https://payedigesadat.com/",
      },
      {
        id: uniqueId(),
        image: "/images/1-4-proland.jpg",
        name: "سوپر پروتئین پرولند",
        alt: "سایت سوپر پروتئین پرولند - طراحی شده با ویترین",
        link: "https://prolandprotein.ir/",
      },
      {
        id: uniqueId(),
        image: "/images/1-11-soofche.jpg",
        name: "ادویه سوفچه",
        alt: "سایت ادویه سوفچه - طراحی شده با ویترین",
        link: "https://sofcheh.ir/",
      },
      {
        id: uniqueId(),
        image: "/images/6-5-greenseed.jpg",
        name: "دانه ی سبز",
        alt: "سایت دانه ی سبز - طراحی شده با ویترین",
        link: "https://greenseedshop.ir",
      },
      {
        id: uniqueId(),
        image: "/images/6-6-nespresso.jpg",
        name: "نسپرسو تهران",
        alt: "سایت نسپرسو تهران - طراحی شده با ویترین",
        link: "https://nespressotehran.ir",
      },
      {
        id: uniqueId(),
        image: "/images/1-1-cakekhoone.jpg",
        name: "کیک خونه",
        alt: "سایت کیک خونه - طراحی شده با ویترین",
        link: "https://cakeekhooneh.com/",
      },
      {
        id: uniqueId(),
        image: "/images/1-7-galaxy.jpg",
        name: "کیک خونگی گلکسی",
        link: "https://cakekhonegi.com/",
        alt: "سایت کیک خونگی گلکسی - طراحی شده با ویترین",
      },
      {
        id: uniqueId(),
        image: "/images/8-3-marysbakery.jpg",
        name: " نان و شیرینی ماری",
        link: "https://marysbakery.ir",
        alt: "سایت نان و شیرینی ماری - طراحی شده با ویترین",
      },
    ],
  },

  {
    id: uniqueId(),
    label: "clothing",
    title: "پوشاک",
    logo: "/images/Clothing.png",
    items: [
      {
        id: uniqueId(),
        image: "/images/4-1-gilasis.jpg",
        name: "گیلاسیس",
        alt: "سایت گیلاسیس - طراحی شده با ویترین",
        link: "https://gilasis.ir/",
      },
      {
        id: uniqueId(),
        image: "/images/4-2-poone.jpg",
        name: "Poone Clothing",
        alt: "سایت Poone Clothing - طراحی شده با ویترین",
        link: "https://pooneclothing.ir/",
      },
      {
        id: uniqueId(),
        image: "/images/4-3-jutehomeland.jpg",
        name: "جوت هوملند",
        alt: "سایت جوت هوملند - طراحی شده با ویترین",
        link: "https://jutehomeland.ir/",
      },
      {
        id: uniqueId(),
        image: "/images/4-4-boojanshop.jpg",
        name: "بوژان شاپ",
        alt: "سایت بوژان شاپ - طراحی شده با ویترین",
        link: "https://boojanshop.com/",
      },
      {
        id: uniqueId(),
        image: "/images/4-5-jeandarc.jpg",
        name: "شال و روسری ژاندارک",
        link: "https://jeannedarc-scarf.com/",
        alt: "سایت شال و روسری ژاندارک - طراحی شده با ویترین",
      },
      {
        id: uniqueId(),
        image: "/images/9-1-saraborn.jpg",
        name: "سارا بُرن",
        link: "https://saraborn.ir/",
        alt: "سایت سارا بُرن - طراحی شده با ویترین",
      },
    ],
  },
];
