import moment from "moment";

const date = moment().add(2, "day");
date.set({ hour: 15, minute: 30, second: 0, millisecond: 0 });
export const mockOrder = (status) => ({
  id: "mock",
  order_id: "8994536",
  order_number: 301,
  user_id: 95775,
  description: "لطفا موقع تحویل زنگ ۲ رو بزنید.",
  submitted_at: 1629111217264.0,
  business_id: 178415,
  business_site_domain: "olddowntown",
  payment_status: 2,
  order_status: status || 0,
  sales_channel: 0,
  items: [
    {
      amount: 1,
      returned: 0,
      deal: {
        id: 1992343,
        pos_id: null,
        pos_code: null,
        title: "محصول تستی ۰۱",
        description: "<p>لورم ایپسوم ...</p>",
        final_unit_cost: 0.0,
        initial_price: 44500,
        discounted_price: 44500,
        super_deal_id: null,
        categories: ["دسته بندی"],
        main_image_thumbnail_url:
          "https://hs3-cdn-saas.behtarino.com/media/CACHE/images/business_deals_images/57716/d370583e98637f348174743d96c31604.jpg",
        packaging_price: 2000,
        weight: 0,
        extra_items: [
          { id: null, title: "کارت پستال", price: 5000, amount: 1 },
        ],
        modifiers: [
          {
            modifier_id: "LXJBA4CHJV45SCFFEJ1OLRIJ9P26FDDS",
            modifier_set: 4473,
            title: "کارت پستال",
            price: 5000,
            amount: 1,
            final_unit_cost: 0.0,
            ingredients: [],
          },
        ],
        ingredients: [],
        variation_id:
          "F2VSVDL2EW7YVTQO6Q8DG5XWWGPBUDP6-H03WG13I9FYQ3KSHJV6JUMIVA27OU410",
        variation_name: " مشکی بزرگ",
      },
    },
  ],
  total_weight: 0,
  pos_user_id: 95775,
  pos_device_id: null,
  total_initial_price: 49500,
  total_items_price: 49500,
  final_items_price: 49500,
  delivery_price: 4500,
  total_packaging_price: 5000,
  taxing_price: 0,
  total_discount: 0,
  discount_from_items: 0,
  discount_code_amount: 0,
  wallet_credit_used: 0,
  gift_credit_used: 0,
  final_cost: 0,
  final_price: 59000,
  total_price: 59000,
  paid_price: 0,
  should_pay: 59000,
  is_carry_out_order: false,
  delivery_on_site: false,
  delivery_on_site_description: "",
  delivery_site_type: "delivery_on_user_site",
  is_delivery_on_site: false,
  is_carry_out: false,
  delivery_timing_type: "fast",
  delivery_time: null,
  absolute_delivery_time: null,
  delivery_title: "ارسال سریع با پذیرش پیش سفارش",
  delivery_pricing_type: "rate_by_price",
  user_address: {
    name: "جهانگیری",
    phone: "*******0912",
    address:
      "تهران، محله تیموری، محمدعلی حبیب الله، جنب میدان دکتر حسن حسینی - پلاک ۱- کد پستی 1234567890",
    latitude: 35.7067442,
    longitude: 51.3555661,
    number: null,
    unit: null,
    postal_code: "1234567890",
  },
  deliverer_name: null,
  deliverer_phone: "",
  delivery_interval: { from_time: date.unix(), to_time: date.unix() + 1800 },
  alopeyk_token: null,
  delivery_companies_data: null,
  _order_history: [
    {
      log_type: "created",
      pos_user_id: null,
      pos_device_id: null,
      created_at: "2021-08-16T15:23:37.711000+04:30",
      order: {
        items: [
          {
            amount: 1,
            returned: 0,
            deal: {
              id: 1992343,
              pos_id: null,
              pos_code: null,
              title: "محصول تستی ۰۱",
              description: "<p>لورم ایپسوم ...</p>",
              final_unit_cost: 0.0,
              initial_price: 44500,
              discounted_price: 44500,
              super_deal_id: null,
              categories: ["دسته بندی"],
              main_image_thumbnail_url:
                "https://hs3-cdn-saas.behtarino.com/media/CACHE/images/business_deals_images/57716/d370583e98637f348174743d96c31604.jpg",
              packaging_price: 2000,
              weight: 0,
              extra_items: [
                { id: null, title: "کارت پستال", price: 5000, amount: 1 },
              ],
              modifiers: [
                {
                  modifier_id: "LXJBA4CHJV45SCFFEJ1OLRIJ9P26FDDS",
                  modifier_set: 4473,
                  title: "کارت پستال",
                  price: 5000,
                  amount: 1,
                  final_unit_cost: 0.0,
                  ingredients: [],
                },
              ],
              ingredients: [],
              variation_id:
                "F2VSVDL2EW7YVTQO6Q8DG5XWWGPBUDP6-H03WG13I9FYQ3KSHJV6JUMIVA27OU410",
              variation_name: " مشکی بزرگ",
            },
          },
        ],
        _final_cost: null,
        _final_price: 0,
        _total_packaging_price: null,
        _delivery_price: null,
        _taxing_price: null,
        _total_weight: null,
        description: "لطفا موقع تحویل زنگ ۲ رو بزنید.",
        delivery_site_type: "delivery_on_user_site",
        delivery_time: null,
        deliverer_name: null,
        delivery_title: "ارسال سریع با پذیرش پیش سفارش",
        delivery_timing_type: "fast",
        delivery_rule_id: 8031,
        delivery_pricing_type: "rate_by_price",
        user_address: {
          name: "جهانگیری",
          phone: "*******0912",
          address:
            "تهران، محله تیموری، محمدعلی حبیب الله، جنب میدان دکتر حسن حسینی - پلاک ۱- کد پستی 1234567890",
          latitude: 35.7067442,
          longitude: 51.3555661,
          number: null,
          unit: null,
          postal_code: "1234567890",
          national_id: null,
        },
        delivery_interval: { from_time: 1629111600, to_time: 1629113400 },
        delivery_companies_data: null,
      },
    },
  ],
  crm_membership: 705298,
});
